---
abstract: 'A light-weight, nerdy, smart CMS in perl based on Perl Dancer2 framework.'
author:
  - "Simone Fare' <cymon@tiscali.it>"
build_requires:
  FindBin: 0
  LWP::UserAgent: 0
  Test::More: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Strehler
requires:
  Authen::Passphrase::BlowfishCrypt: 0
  Carp: 0
  Cwd: 0
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  DBIx::Class::Schema::Loader: 0
  DBIx::Class::TimeStamp: 0
  Dancer2: 0.11
  Dancer2::Core::App: 0
  Dancer2::Core::Runner: 0
  Dancer2::Plugin: 0
  Dancer2::Plugin::Ajax: 0
  Dancer2::Plugin::DBIC: 0
  Dancer2::Serializer::JSON: 0
  DateTime::Format::SQLite: 0
  DateTime::Format::Strptime: 0
  File::Copy: 0
  File::Copy::Recursive: 0
  File::Path: 0
  HTML::FormFu: 1.00
  HTML::FormFu::Element::Block: 0
  HTML::FormFu::Element::Fieldset: 0
  HTML::FormFu::Element::Label: 0
  HTML::FormFu::Element::Select: 0
  HTML::FormFu::Element::Text: 0
  HTML::FormFu::Validator: 0
  Lingua::EN::Inflect: 0
  Moo: 0
  Moo::Role: 0
  Moose: 0
  SQL::Translator: 0
  Term::ReadKey: 0
  Text::Unidecode: 0
  Unicode::Normalize: 0
  YAML::XS: 0
version: 1.2.0
